AS	=	as
LD	=	ld
OBJCOPY	=	objcopy

BOOTLOADEROBJARCH	=	--32
BOOTLOADERARCH	=	-m elf_i386

OBJCOPYFORMAT	=	-O binary

DEBUG	=	-g

LDTTEXT	=	-T bootloader.ld

BOOTLOADEROBJ	=	bootloader.o
BOOTLOADERSRC	=	bootloader.s

BOOTLOADERELF	=	bootloader.elf
BOOTLOADERBIN	=	bootloader.bin

all	:	$(BOOTLOADERBIN)

$(BOOTLOADERBIN)	:	$(BOOTLOADEROBJ)
	$(LD) $(BOOTLOADEROBJ) $(LDTTEXT) $(BOOTLOADERARCH) $(DEBUG) -o $(BOOTLOADERELF)
	$(OBJCOPY) $(OBJCOPYFORMAT) $(BOOTLOADERELF) $(BOOTLOADERBIN)

$(BOOTLOADEROBJ)	:	$(BOOTLOADERSRC)
	$(AS) $(BOOTLOADERSRC) $(BOOTLOADEROBJARCH) -o $(BOOTLOADEROBJ) $(DEBUG)

clean	:	
	rm -rf $(BOOTLOADERBIN) $(BOOTLOADERELF) $(BOOTLOADEROBJ)
